### ISSUE TITLE
Integrate ui with app control

### ISSUE THREAD

**Issue by shamlikt** [shamlikt/Hwacha#24]
Integrate ui with app control and rewrite app control layer

**Comment by simsarulhaqv** [comment]
@nithin-cp , you need not import ui to socialMediaController. Instead, use the APIs provided by the socialMediaController to get things done in UI Layer. If existing APIs are not enough post an issue.

**Comment by simsarulhaqv** [comment]
@nithin-cp , make sure library codes are not specific to a particular interface. We need the same library for integrating with PyQt interface as well.

**Comment by simsarulhaqv** [comment]
What is the status of this issue @nithin-cp @shamlikt ?

**Comment by shamlikt** [comment]
Terminal ui integrated
