### ISSUE TITLE
integration and testing

### ISSUE THREAD

**Issue by shamlikt** [shamlikt/Hwacha#26]

**Comment by simsarulhaqv** [comment]
@shamlikt 
1) How is the integration part of this issue different from #24 ? Please specify further details
2) In order to do testing part, it is necessary that #24 is closed.

This issue is in stuck right now. Please comment ASAP

**Comment by shamlikt** [comment]
We need to integrate appControl with smControl and broadcast .

**Comment by shamlikt** [comment]
fixes
