### ISSUE TITLE
No setup for a fresh respository.

### ISSUE THREAD

**Issue by nibrahim** [shamlikt/Hwacha#8]
After just cloning the code and running `py.test` in the top level directory, I see this error

```
Hwacha/test_broadcast.py:1: in <module>
    import broadcast
Hwacha/broadcast.py:1: in <module>
    import tweepy
E   ImportError: No module named tweepy
```

You can fix this by either putting these in your `setup.py` like mentioned [here ](http://python-packaging.readthedocs.org/en/latest/dependencies.html) or by including a `requirements.txt` file. There is a comparison betwen the two approaches [here](https://caremad.io/2013/07/setup-vs-requirement/). 

The upshot is that it should be clear how to set up an environment for someone fresh to the project.

**Comment by shamlikt** [comment]
closed
