### ISSUE TITLE
Tests don't run properly

### ISSUE THREAD

**Issue by nibrahim** [shamlikt/Hwacha#9]
After manually installed tweepy (#8). I just ran py.test and tried to see what was happening. There were just 3 tests and all of them failed with something like this.

```
Traceback (most recent call last):
  File "/tmp/Hwacha/Hwacha/test_broadcast.py", line 14, in test_broadcst
    push = broadcast.broadcastmessage('Hello Hwacha123d',soc_media,key) #Dont repeate message
  File "/tmp/Hwacha/Hwacha/broadcast.py", line 109, in broadcastmessage
    soc_media={'twitter':init_twitter(message,key),
  File "/tmp/Hwacha/Hwacha/broadcast.py", line 86, in init_twitter
    access_token_secret = key['acces s_token_secret']
KeyError: 'acces s_token_secret'
```

Your tests should run. YOu don't _really_ need the `access_token_secret` and other things to unit test your code. You can use the [mock](https://pypi.python.org/pypi/mock) library to test your twitter code without actually connecting to the network.

**Comment by shamlikt** [comment]
we used single user OAuth in our application. so user need to update keys manually

**Comment by nibrahim** [comment]
You don't need OAuth or even any of the tweepy code to run to verify your own code. Like I said, take a look at the mock library. If it's not clear, we can discuss this on the mailing list.

**Comment by nibrahim** [comment]
It's a good idea to just say "fixes #9" in your commit message. That will automatically close bugs and track which commit fixes them. Since this doesn't have that, please update it manually.

**Comment by simsarulhaqv** [comment]
I have already committed. How to update it manually?

**Comment by nibrahim** [comment]
Just add a comment here with a link to the commit hash.
